import Footer from "@/components/Common/Footer";
import Header from "@/components/Common/Header";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Infinite Loop",
  description: "Generated by create next app",
};

const CommonLayout = async ({ children }: { children: React.ReactNode }) => {
  return (
    <div>
      <div className=" container mx-auto">
        <Header />

        <div className=" ">{children}</div>
      </div>
      <Footer />
    </div>
  );
};

export default CommonLayout;
